server:
  port: 8195
  servlet:
    context-path: /market-comment
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

integrations:
  product-service:
    url: http://localhost:8189/market-core/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000
  auth-service:
    url: http://localhost:8187/market-auth/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000
