//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.08 at 12:32:58 PM MSK 
//


package ru.agile.scrum.mst.market.stock.soap.productstocks;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.flamexander.spring.ws.productstocks package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.flamexander.spring.ws.productstocks
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateProductStocksDBRequest }
     * 
     */
    public UpdateProductStocksDBRequest createUpdateProductStocksDBRequest() {
        return new UpdateProductStocksDBRequest();
    }

    /**
     * Create an instance of {@link ProductStock }
     * 
     */
    public ProductStock createProductStock() {
        return new ProductStock();
    }

    /**
     * Create an instance of {@link UpdateProductStocksDBResponse }
     * 
     */
    public UpdateProductStocksDBResponse createUpdateProductStocksDBResponse() {
        return new UpdateProductStocksDBResponse();
    }

}
