server:
  port: 8190
  servlet:
    context-path: /market-cart
integrations:
  product-service:
    url: http://core-service:8189/market-core/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000
spring:
  redis:
    host: redis
