server:
  port: 8189
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-market-core;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  flyway:
    locations: classpath:/db/test